using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AbilityActivateOnHit : MonoBehaviour
{
    private AbilityEvents _events;

    private void Start()
    {
        Subscribe();
    }

    private void Awake()
    {
        _events = GetComponent<AbilityEvents>();
    }

    private void OnDisable()
    {
        Unsubscribe();
    }

    private void Activate(Collider2D collider)
    {
        if(collider.gameObject.tag != "Player")
        {
            _events.Activate();
        }
    }

    private void Subscribe()
    {
        _events._onHit += Activate;
    }

    private void Unsubscribe()
    {
        _events._onHit -= Activate;
    }
}
